"""empty message

Revision ID: 955c296dd72a
Revises: df20b2753980
Create Date: 2025-04-08 01:06:00.183094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955c296dd72a'
down_revision = 'df20b2753980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
