"""empty message

Revision ID: c296bb24a4c0
Revises: 0074a12189d2
Create Date: 2025-04-11 22:36:25.480541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c296bb24a4c0'
down_revision = '0074a12189d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planet_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_planet_character_id_fkey', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
