"""empty message

Revision ID: df20b2753980
Revises: 051e29a1b421
Create Date: 2025-04-07 23:10:48.176172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df20b2753980'
down_revision = '051e29a1b421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=30), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('landscape', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('landscape')
        batch_op.drop_column('age')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('species')

    # ### end Alembic commands ###
